import = [
  "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
]

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
size = 11.25
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

